version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalogapi:
    image: eventbrite/eventcatalogapi
    build:
      context: .\EventCatalogAPI/
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=EventCatalogDB;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      ExternalBaseUrl: http://localhost:7001
    ports:
      - "7001:80"
    container_name: eventbriteeventcatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  tokenserver:
    image: eventbrite/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=tokensqlserver;Initial Catalog=TokenServiceDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      MvcClient: http://localhost:7502
    ports:
      - "7900:80"
    container_name: eventbritetokenapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokensqlserver

  cart:
    image: eventbrite/cartapi
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options: {
        max-size: "200k",
        max-file: "10"
      }
    environment:
      IdentityUrl: http://192.168.5.150:7900
      ConnectionString: basket.data
    ports:
      - "7009:80"
    container_name: eventscartapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - basket.data
      - rabbitmq

  order:
    image: eventbrite/orderapi
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options: {
        max-size: "200k",
        max-file: "10"
      }
    environment:
      IdentityUrl: http://192.168.5.150:7900
      ConnectionString: "Data Source=ordersqlserver;Initial Catalog=OrdersDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
    ports:
      - "7021:80"
    container_name: eventsorderapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - ordersqlserver
      - rabbitmq

  WebMvc:
    image: eventbrite/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options: {
        max-size: "200k",
        max-file: "10"
      }
       
     
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventCatalogUrl: http://eventcatalogapi
      IdentityUrl: http://192.168.5.150:7900
      CallBackUrl: http://localhost:7502
      CartUrl: http://cart
      Orderurl: http://order
      StripePublicKey:  pk_test_51MTyUDHY3OX11gRaXmtt8uFyMdidrrM3qkjYkd4RZUlxoZCXiKooRWCI7DhzxbMxucYtbM9d1djN9ltaWI3lTd6B00okMNBNjM
      StripePrivateKey: sk_test_51MTyUDHY3OX11gRaoEYLtdM4oFufrBiHjXUP0tosKenjunBdpbrQAxBKQiskwy4ati5B0eufLbFtbd2kavsSXbhh001ZJSkfz3 
    ports:
      - "7502:80"
    container_name: eventwebshop
    networks:
      - frontend
    depends_on:
      - eventcatalogapi
      - tokensqlserver
      - cart
      - order


  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
      SA_PASSWORD: ProductApi123(!)
    ports:
      - "1498:1433"
    container_name: eventbritesqlserver
    networks:
      - backend

  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
      SA_PASSWORD: ProductApi123(!)
    ports:
      - "1428:1433"
    container_name: eventstokensqlserver
    networks:
      - backend

  ordersqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
      SA_PASSWORD: ProductApi123(!)
    ports:
      - "1450:1433"
    container_name: eventsordersqlserver
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "7051:6379"
    container_name: eventbasketdata
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    networks:
      - backend 